services:
  haproxy:
    image: haproxy:latest
    # ports:
    # - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    restart: always

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  cloudflared:
    image: cloudflare/cloudflared
    command:
      - tunnel
      - --no-autoupdate
      - run
    environment:
      - TUNNEL_TOKEN=
      - TUNNEL_TRANSPORT_PROTOCOL=http2
    restart: always

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
